### ISSUE TITLE
dplyr/dbplyr mutate/case_when

### ISSUE THREAD

**Issue by tslumley** [hannesmuehleisen/MonetDBLite-R#5] opened 2017-11-06 02:54 UTC
The code

```
library(DBI)
library(dplyr)
library(dbplyr)
con <- dbConnect(MonetDBLite::MonetDBLite())
#con <- dbConnect(RSQLite::SQLite())
data(iris)
names(iris)<-tolower(sub("\\.","_",names(iris)))
dbWriteTable(con,"iris_table",iris)
irisdb<-tbl(con,"iris_table")

mutate(irisdb, sepal_category = case_when(sepal_length>5.5~"long", sepal_length>5~"medium", TRUE~"short")) 
```

gives the error
```
Error: Columns `sepal_length`, `sepal_width`, `petal_length`, `petal_width`, `species` must be length 1 or 150, not 10, 10, 10, 10, 10
```

This could also be a dplyr/dbplyr bug, but using RSQLite instead of MonetDBLite (as with the commented-out line above) doesn't give the error, so I thought I should at least mention it here.

**Comment by hannesmuehleisen** [comment] 2017-11-06 06:09
There seems to be indeed an issue with MonetDBLite here. When sending the query dplyr generates, R notes a "corrupt data frame" in the result:

```
res <- dbGetQuery(con, 'SELECT "sepal_length", "sepal_width", "petal_length", "petal_width", "species", CASE WHEN ("sepal_length" > 5.5) THEN (\'long\') WHEN ("sepal_length" > 5.0) THEN (\'medium\') WHEN (TRUE) THEN (\'short\') END AS "sepal_category" FROM "iris_table" LIMIT 10')

> print(res)
   sepal_length sepal_width petal_length petal_width species sepal_category
1           5.1         3.5          1.4         0.2  setosa         medium
[...]
Warning message:
In format.data.frame(x, digits = digits, na.encode = FALSE) :
  corrupt data frame: columns will be truncated or padded with NAs
```
The `sepal_category` has length 150, not 10 (as dictated by the `LIMIT`). So something going wrong in result conversion I suppose. Sorry for that, will fix.

**Comment by hannesmuehleisen** [comment] 2017-11-06 11:54
Should be fixed now. Thanks for providing the reproducible example, I have also added this as a test case.

**Closed** 2017-11-06 15:09 UTC
Labels: bug
